# From Python lists to PyTorch tensors

In [1]:
a = [1.0,2.0,1.0]

In [2]:
a[0]

In [3]:
a[2]

1.0

In [4]:
a

[1.0, 2.0, 1.0]

In [5]:
a[2] = 3.0

In [6]:
a

[1.0, 2.0, 3.0]

## constructing our first tensors

In [7]:
import torch 
a = torch.ones(3)

In [8]:
a

tensor([1., 1., 1.])

In [9]:
a[1]

tensor(1.)

In [10]:
a[2] = 2.0

In [11]:
a

tensor([1., 1., 2.])

In [12]:
points = torch.zeros(6)

In [13]:
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

In [14]:
points

tensor([4., 1., 5., 3., 2., 1.])

In [15]:
points = torch.tensor([4.0,1.0,5.0,3.0,2.0,1.0])

In [16]:
points

tensor([4., 1., 5., 3., 2., 1.])

In [17]:
float(points[0]),float(points[1])

(4.0, 1.0)

In [18]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])

In [19]:
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [20]:
points.shape

torch.Size([3, 2])

In [21]:
points = torch.zeros(3,2)

In [22]:
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [23]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])

In [24]:
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [25]:
points[0,1]

tensor(1.)

In [26]:
points[0]

tensor([4., 1.])

## Indexing tensors

In [27]:
some_list = list(range(6))
some_list[:]
some_list[1:4]
some_list[1:]
some_list[:4]
some_list[:-1]
some_list[1:4:2]

[1, 3]

In [28]:
points[1:]
points[1:,:]
points[1:,0]
points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

## Named tensors

In [29]:
img_t = torch.randn(3,5,5) # shape[chanels,rows,columns]

In [30]:
img_t

tensor([[[ 0.0143, -0.5601,  1.4701,  0.7323,  1.7594],
         [ 1.1547,  1.7645,  0.5195, -0.3002, -1.6590],
         [ 0.6667, -0.6774, -0.3013, -1.5211,  0.8394],
         [-1.4677, -1.4021,  0.0749,  0.3053,  0.4913],
         [-1.4832, -0.2745,  0.9809, -0.5049, -1.2001]],

        [[-0.0356, -0.4242, -0.5207,  0.2323,  1.2421],
         [ 1.2221,  0.1900, -2.9227, -0.3839, -1.8370],
         [-0.6060,  0.7484, -0.1079, -2.8168,  1.9551],
         [-0.7102,  0.0547, -1.1705, -0.0333,  0.9804],
         [-0.9894,  0.7440,  0.9688,  0.3668,  0.1069]],

        [[ 0.6331,  0.7167, -1.6729, -0.0903, -0.8970],
         [ 1.7188,  0.3052, -0.3337, -0.3316,  0.4362],
         [-1.1217, -0.1170,  0.1412, -0.6311, -2.1857],
         [ 0.4438, -1.0864,  1.1904, -1.0602, -1.7966],
         [-0.2584, -1.6671,  0.0861,  0.5065,  2.2468]]])

In [31]:
weights = torch.tensor([0.2126,0.7152,0.0722])

In [32]:
weights

tensor([0.2126, 0.7152, 0.0722])

In [33]:
batch_t = torch.randn(2,3,5,5) #shape[batch,channels,rows,columns]

In [34]:
batch_t

tensor([[[[ 0.8586, -1.2570, -0.2880, -0.6115,  0.4269],
          [-0.9780,  0.3388,  0.4432,  0.2703,  1.8397],
          [ 0.8903, -1.6878, -0.6726, -0.6574, -0.5588],
          [ 0.1307,  0.4138, -0.1888,  0.6448,  0.8660],
          [-1.3752,  0.2487,  0.5129,  1.9458, -0.7578]],

         [[-1.7222,  0.3900,  0.0860, -0.1482, -2.0505],
          [ 0.3399, -1.3244, -0.7877, -1.1779,  0.8569],
          [-0.6185, -0.0108,  0.4420,  0.5758,  0.1813],
          [-3.0146, -0.7466,  1.2487, -0.0718, -0.5843],
          [ 0.0405, -0.3011, -0.0456,  0.4780,  0.3620]],

         [[-1.5571,  0.4839,  0.1741, -1.3382,  1.4766],
          [-0.3787, -0.5085, -0.3902, -1.0400, -0.8347],
          [-0.0446, -0.5588,  0.9611, -0.6148,  0.4677],
          [-0.6414, -0.9752, -0.2538,  0.5707,  1.1558],
          [ 0.6425,  0.0521,  2.7017,  0.6188,  0.7726]]],


        [[[-0.6102,  0.1559,  0.1597,  0.5319,  1.5850],
          [ 1.5631,  0.2697, -1.2324, -0.5572, -1.8098],
          [-0.4851,  2.

In [35]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape,batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [36]:
img_gray_naive

tensor([[ 0.2039, -0.0892, -0.2412,  0.2914,  0.7015],
        [ 1.3652,  0.7532, -0.9123, -0.3386, -1.0199],
        [-0.3537, -0.0153, -0.0893, -1.6563,  0.2029],
        [-0.5781, -0.8112,  0.0316, -0.2627, -0.1083],
        [-0.9103, -0.3992,  0.6786,  0.1228,  0.3845]])

In [37]:
batch_gray_naive

tensor([[[-8.0691e-01, -1.2771e-01, -9.3037e-03, -6.9929e-01, -4.9011e-02],
         [-3.3896e-01, -4.9806e-01, -2.4492e-01, -6.4918e-01,  6.2064e-01],
         [ 7.5731e-02, -7.5246e-01,  2.4352e-01, -2.3213e-01,  3.0048e-02],
         [-1.1751e+00, -4.3603e-01,  2.6870e-01,  3.8122e-01,  4.7918e-01],
         [-2.3072e-01, -7.5305e-05,  1.0563e+00,  1.0142e+00,  1.2561e-01]],

        [[ 1.0994e-01,  5.6151e-01, -4.1732e-01,  3.1991e-01, -4.9317e-02],
         [ 6.9815e-01,  2.0869e-01, -1.7358e-01,  4.5747e-01, -3.9331e-01],
         [-4.9282e-01,  1.7051e+00,  1.6958e-02, -2.8869e-01,  2.6507e-01],
         [ 2.6738e-01, -7.5258e-01, -6.8624e-01, -1.0997e+00, -2.0883e-01],
         [ 7.9113e-01,  3.8433e-01,  2.0221e-01, -7.0978e-01, -3.2017e-01]]])

In [38]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
img_weights = (img_t*unsqueezed_weights)
batch_weights = (batch_t*unsqueezed_weights)
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
batch_weights.shape,batch_t.shape,unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [40]:
weights.shape

torch.Size([3])

In [41]:
unsqueezed_weights

tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]])

In [43]:
img_gray_weighted_fancy = torch.einsum('...chw,c->hw',img_t,weights)
batch_gray_weighted_fancy = torch.einsum('...chw,c->...hw',batch_t,weights)
batch_gray_weighted_fancy.shape

torch.Size([2, 5, 5])

In [44]:
weights_named = torch.tensor([0.2125,0.7152,0.0722],names=['channels'])

<ipython-input-44-5e700b958446>:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\c10/core/TensorImpl.h:1463.)
  weights_named = torch.tensor([0.2125,0.7152,0.0722],names=['channels'])


In [45]:
weights_named

tensor([0.2125, 0.7152, 0.0722], names=('channels',))

In [46]:
img_named = img_t.refine_names(...,'channels','rows','columns')

In [47]:
batch_named = batch_t.refine_names(...,'channels','rows','columns')


In [48]:
print("img named:",img_named.shape,img_named.names)
print("batch named:",batch_named.shape,batch_named.names)

img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [49]:
weights_aligned = weights_named.align_as(img_named)
weights_aligned.shape,weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [50]:
gray_named = (img_named*weights_aligned).sum('channels')

In [51]:
gray_named.shape,gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

In [52]:
gray_plain = gray_named.rename(None)
gray_plain.shape,gray_plain.names

(torch.Size([5, 5]), (None, None))

In [53]:
double_points = torch.ones(10,2,dtype=torch.double)
short_points = torch.tensor([[1,2],[3,4]],dtype=torch.short)

In [54]:
short_points.dtype

torch.int16

In [55]:
double_points = torch.zeros(10,2).double()
short_points = torch.ones(10,2).short()

In [57]:
double_points = torch.zeros(10,2).to(torch.double)
short_points = torch.ones(10,2).to(dtype=torch.short)

In [59]:
points_64 = torch.rand(5,dtype=torch.double)
points_short= points_64.to(torch.short)

In [60]:
points_64*points_short

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

## The tensor API

In [61]:
a = torch.ones(3,2)
a_t = torch.transpose(a,0,1)

In [62]:
a.shape,a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [63]:
a = torch.ones(3,2)
a_t = a.transpose(0,1)

In [64]:
a.shape,a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

## Indexing into storage

In [65]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])

In [67]:
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [68]:
points_storage = points.storage()
points_storage[0]

4.0

In [69]:
points.storage()[1]

1.0

In [70]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])

In [71]:
points_storage = points.storage()

In [72]:
points_storage[0]=2.0

In [73]:
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

## Modifying stored values:In-place operations

In [74]:
a = torch.ones(3,2)
a.zero_()

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

## views of another tensor's storage

In [75]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])

In [76]:
second_point = points[1]
second_point.storage_offset()

2

In [77]:
second_point.shape

torch.Size([2])

In [78]:
second_point

tensor([5., 3.])

In [79]:
points.stride()

(2, 1)

In [80]:
# The stride is a tuple indicating the number of elements in the storage that have to be skipped when the index is increased by 1 in 
# each dimension

In [81]:
second_point = points[1]
second_point.size()

torch.Size([2])

In [82]:
second_point.storage_offset()

2

In [83]:
second_point.stride()

(1,)

In [84]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])

In [85]:
second_point = points[1]

In [86]:
second_point[0] = 10.0

In [87]:
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [88]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])

In [89]:
second_point = points[1].clone()


In [90]:
second_point[0] = 10.0

In [91]:
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

## Transposing without copying

In [92]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])

In [94]:
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [95]:
points.size

<function Tensor.size>

In [96]:
points.size()

torch.Size([3, 2])

In [97]:
points_t = points.t()

In [98]:
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [99]:
id(points.storage()) == id(points_t.storage())

False

In [100]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [101]:
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [102]:
id(points.storage()) == id(points_t.storage())

False

In [103]:
points.stride()

(2, 1)

In [104]:
points_t.stride()

(1, 2)

In [105]:
# pytorch 中的storage指的是连续的内存块，而tensor则是映射到 storage的视图，他把单条的内存区域映射成了n维的空间视图
# size 是tensor的维度，storage offset是数据在storagge中的索引，stride是storage中对应于tensor的相邻维度间第一个索引的跨度。
# 3,1,2,4,1，f
# 与它对应的tensor
# 3,1,2
# 4,1,f
# 那么这里的stride=(3,1),因为从第一行的第一个索引到第二行第一个索引的跨度是3，从第一列到第二列的跨度是1

## Transposing in higher dimension

In [106]:
some_t = torch.ones(3,4,5)
transpose_t = some_t.transpose(0,2)
some_t.shape

torch.Size([3, 4, 5])

In [107]:
some_t

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [108]:
transpose_t.shape

torch.Size([5, 4, 3])

In [109]:
transpose_t

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [110]:
some_t.stride()

(20, 5, 1)

In [111]:
transpose_t.stride()

(1, 5, 20)

## contiguous tensors

In [112]:
points.is_contiguous()

True

In [113]:
points_t.is_contiguous()

False

In [114]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])

In [115]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [116]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [117]:
points_t.stride()

(1, 2)

In [119]:
points_t.shape

torch.Size([2, 3])

## Moving tensors to the GPU
### Managing a tensor's device attribute

In [3]:
points_gpu = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]],device='cuda')

In [2]:
import torch

In [5]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])

In [6]:
points_gpu = points.to(device='cuda')

In [7]:
points_gpu = points.to(device='cuda:0')

In [8]:
points = 2*points

In [9]:
points_gpu = 2*points.to(device='cuda')

In [10]:
points_gpu = points_gpu +4

In [11]:
points_gpu

tensor([[20.,  8.],
        [24., 16.],
        [12.,  8.]], device='cuda:0')

In [12]:
points

tensor([[ 8.,  2.],
        [10.,  6.],
        [ 4.,  2.]])

In [13]:
points_cpu = points_gpu.to(device='cpu')

In [14]:
points_gpu = points.cuda()
points_gpu = points.cuda(0)

In [15]:
points_cpu = points_gpu.cpu()

In [16]:
points = torch.ones(3,4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [17]:
points = torch.from_numpy(points_np)

In [18]:
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
torch.save(points,'../data/p1ch3/outpoints.t')

In [20]:
with open('../data/p1ch3/ourpoints.t','wb') as f:
    torch.save(points,f)

In [21]:
points = torch.load('../data/p1ch3/ourpoints.t')

In [22]:
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
with open('../data/p1ch3/ourpoints.t','rb') as f:
    points = torch.load(f)

In [24]:
import h5py

In [25]:
f = h5py.File('../data/p1ch3/ourpoints.hdf5','w')

In [26]:
dset = f.create_dataset('coords',data=points.numpy())
f.close()

In [27]:
f = h5py.File('../data/p1ch3/ourpoints.hdf5','r')
dset=f['coords']
last_points = dset[-2:]

In [28]:
last_points = torch.from_numpy(dset[-2:])
f.close()